export const FAKE_MOVIE_DATA = [
    {
       "id":"13166",
       "title":"Feito Na América",
       "originalTitle":"American Made",
       "inPreSale":false,
       "duration":"115",
       "contentRating":"16 anos",
       "distributor":"Universal Pictures",
       "urlKey":"feito-na-america",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/feito-na-america",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/feito-na-america#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/13166-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/13166-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=FZCfEGYriz8",
             "embeddedUrl":"//www.youtube.com/embed/FZCfEGYriz8"
          }
       ],
       "genres":[
          "Drama"
       ],
       "tags":[
          "Em Alta"
       ],
       "rooms":[
          {
             "name":"Sala 2",
             "sessions":[
                {
                   "id":"53978356",
                   "price":51.3,
                   "type":[
                      "Legendado",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T16:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T16:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:00",
                      "year":"2017"
                   },
                   "time":"16:00",
                   "defaultSector":"00005676",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53978356/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53978359",
                   "price":51.3,
                   "type":[
                      "Legendado",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T19:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T19:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:00",
                      "year":"2017"
                   },
                   "time":"19:00",
                   "defaultSector":"00005676",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53978359/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53978362",
                   "price":51.3,
                   "type":[
                      "Legendado",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T21:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:45",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T21:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:45",
                      "year":"2017"
                   },
                   "time":"21:45",
                   "defaultSector":"00005676",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53978362/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 9",
             "sessions":[
                {
                   "id":"53983019",
                   "price":25.08,
                   "type":[
                      "Legendado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T19:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T19:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:00",
                      "year":"2017"
                   },
                   "time":"19:00",
                   "defaultSector":"00005683",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53983019/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53983010",
                   "price":25.08,
                   "type":[
                      "Legendado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T21:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:45",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T21:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:45",
                      "year":"2017"
                   },
                   "time":"21:45",
                   "defaultSector":"00005683",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53983010/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"18881",
       "title":"Amityville - o despertar",
       "originalTitle":"Amityville: The awakening",
       "inPreSale":false,
       "duration":"85",
       "contentRating":"14 anos",
       "distributor":"Paris Filmes",
       "urlKey":"amityville-o-despertar",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/amityville-o-despertar",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/amityville-o-despertar#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/18881-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/18881-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=E-gkrmNF3mg",
             "embeddedUrl":"//www.youtube.com/embed/E-gkrmNF3mg"
          },
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=UFfzJyYA3iU",
             "embeddedUrl":"//www.youtube.com/embed/UFfzJyYA3iU"
          }
       ],
       "genres":[
          "Terror"
       ],
       "tags":[
          "Em Alta"
       ],
       "rooms":[
          {
             "name":"Sala 10",
             "sessions":[
                {
                   "id":"53976586",
                   "price":25.08,
                   "type":[
                      "Legendado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T22:10:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"22:10",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T22:10:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"22:10",
                      "year":"2017"
                   },
                   "time":"22:10",
                   "defaultSector":"00005684",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53976586/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"19302",
       "title":"It - A coisa",
       "originalTitle":"It",
       "inPreSale":false,
       "duration":"135",
       "contentRating":"16 anos",
       "distributor":"",
       "urlKey":"it-a-coisa",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/it-a-coisa",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/it-a-coisa#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19302-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19302-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=WMJzWJ0rC0w",
             "embeddedUrl":"//www.youtube.com/embed/WMJzWJ0rC0w"
          },
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=sS-wUEF2BLQ",
             "embeddedUrl":"//www.youtube.com/embed/sS-wUEF2BLQ"
          }
       ],
       "genres":[
          "Suspense",
          "Terror"
       ],
       "tags":[
          "Em Alta"
       ],
       "rooms":[
          {
             "name":"Sala 1",
             "sessions":[
                {
                   "id":"53953343",
                   "price":63.83,
                   "type":[
                      "Dublado",
                      "4DX"
                   ],
                   "types":[
                      {
                         "id":64,
                         "name":"4DX",
                         "alias":"4D",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T14:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T14:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:30",
                      "year":"2017"
                   },
                   "time":"14:30",
                   "defaultSector":"00005675",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953343/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953508",
                   "price":63.83,
                   "type":[
                      "Dublado",
                      "4DX"
                   ],
                   "types":[
                      {
                         "id":64,
                         "name":"4DX",
                         "alias":"4D",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T17:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T17:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:30",
                      "year":"2017"
                   },
                   "time":"17:30",
                   "defaultSector":"00005675",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953508/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 1",
             "sessions":[
                {
                   "id":"53953354",
                   "price":63.83,
                   "type":[
                      "Legendado",
                      "4DX"
                   ],
                   "types":[
                      {
                         "id":64,
                         "name":"4DX",
                         "alias":"4D",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T20:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"20:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T20:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"20:30",
                      "year":"2017"
                   },
                   "time":"20:30",
                   "defaultSector":"00005675",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953354/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 5",
             "sessions":[
                {
                   "id":"53953405",
                   "price":27.36,
                   "type":[
                      "Dublado",
                      "Macro XE"
                   ],
                   "types":[
                      {
                         "id":256,
                         "name":"Macro XE",
                         "alias":"Macro XE",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T15:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"15:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T15:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"15:00",
                      "year":"2017"
                   },
                   "time":"15:00",
                   "defaultSector":"00005679",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953405/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 5",
             "sessions":[
                {
                   "id":"53953511",
                   "price":27.36,
                   "type":[
                      "Legendado",
                      "Macro XE"
                   ],
                   "types":[
                      {
                         "id":256,
                         "name":"Macro XE",
                         "alias":"Macro XE",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T18:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"18:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T18:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"18:00",
                      "year":"2017"
                   },
                   "time":"18:00",
                   "defaultSector":"00005679",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953511/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953360",
                   "price":27.36,
                   "type":[
                      "Legendado",
                      "Macro XE"
                   ],
                   "types":[
                      {
                         "id":256,
                         "name":"Macro XE",
                         "alias":"Macro XE",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T21:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T21:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:00",
                      "year":"2017"
                   },
                   "time":"21:00",
                   "defaultSector":"00005679",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953360/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 8",
             "sessions":[
                {
                   "id":"53953422",
                   "price":25.08,
                   "type":[
                      "Dublado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T16:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:45",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T16:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:45",
                      "year":"2017"
                   },
                   "time":"16:45",
                   "defaultSector":"00005682",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953422/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 8",
             "sessions":[
                {
                   "id":"53953446",
                   "price":25.08,
                   "type":[
                      "Legendado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T22:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"22:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T22:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"22:30",
                      "year":"2017"
                   },
                   "time":"22:30",
                   "defaultSector":"00005682",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953446/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"19439",
       "title":"Emoji - O filme",
       "originalTitle":"The Emoji Movie",
       "inPreSale":false,
       "duration":"95",
       "contentRating":"Livre",
       "distributor":"Sony Pictures",
       "urlKey":"emoji-o-filme",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/emoji-o-filme",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/emoji-o-filme#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19439-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19439-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=_9DkUPz3ZT0",
             "embeddedUrl":"//www.youtube.com/embed/_9DkUPz3ZT0"
          },
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=OP9kYDcGEEc",
             "embeddedUrl":"//www.youtube.com/embed/OP9kYDcGEEc"
          }
       ],
       "genres":[
          "Animação"
       ],
       "tags":[
          "Família",
          "Em Alta"
       ],
       "rooms":[
          {
             "name":"Sala 7",
             "sessions":[
                {
                   "id":"53953395",
                   "price":31.92,
                   "type":[
                      "Dublado",
                      "3D"
                   ],
                   "types":[
                      {
                         "id":4,
                         "name":"3D",
                         "alias":"3D",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T15:20:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"15:20",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T15:20:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"15:20",
                      "year":"2017"
                   },
                   "time":"15:20",
                   "defaultSector":"00005681",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953395/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953514",
                   "price":31.92,
                   "type":[
                      "Dublado",
                      "3D"
                   ],
                   "types":[
                      {
                         "id":4,
                         "name":"3D",
                         "alias":"3D",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T17:40:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:40",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T17:40:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:40",
                      "year":"2017"
                   },
                   "time":"17:40",
                   "defaultSector":"00005681",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953514/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953414",
                   "price":31.92,
                   "type":[
                      "Dublado",
                      "3D"
                   ],
                   "types":[
                      {
                         "id":4,
                         "name":"3D",
                         "alias":"3D",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T20:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"20:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T20:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"20:00",
                      "year":"2017"
                   },
                   "time":"20:00",
                   "defaultSector":"00005681",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953414/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"19441",
       "title":"Lino",
       "originalTitle":"Lino",
       "inPreSale":false,
       "duration":"93",
       "contentRating":"Livre",
       "distributor":"20th Century Fox",
       "urlKey":"lino",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/lino",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/lino#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19441-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19441-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=EgKVFWRDvlg",
             "embeddedUrl":"//www.youtube.com/embed/EgKVFWRDvlg"
          }
       ],
       "genres":[
          "Animação"
       ],
       "tags":[
          "Família"
       ],
       "rooms":[
          {
             "name":"Sala 9",
             "sessions":[
                {
                   "id":"53953443",
                   "price":25.08,
                   "type":[
                      "Nacional",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T14:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T14:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:30",
                      "year":"2017"
                   },
                   "time":"14:30",
                   "defaultSector":"00005683",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953443/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953359",
                   "price":25.08,
                   "type":[
                      "Nacional",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T16:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T16:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:30",
                      "year":"2017"
                   },
                   "time":"16:30",
                   "defaultSector":"00005683",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953359/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"19446",
       "title":"O que será de Nozes 2",
       "originalTitle":"The Nut Job 2: Nutty by Nature",
       "inPreSale":false,
       "duration":"91",
       "contentRating":"Livre",
       "distributor":"Diamond Films",
       "urlKey":"o-que-sera-de-nozes-2",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/o-que-sera-de-nozes-2",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/o-que-sera-de-nozes-2#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19446-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19446-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=-eptCcJuL5w",
             "embeddedUrl":"//www.youtube.com/embed/-eptCcJuL5w"
          }
       ],
       "genres":[
          "Animação",
          "Aventura"
       ],
       "tags":[
          "Família",
          "Em Alta"
       ],
       "rooms":[
          {
             "name":"Sala 10",
             "sessions":[
                {
                   "id":"53979047",
                   "price":25.08,
                   "type":[
                      "Dublado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T14:20:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:20",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T14:20:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:20",
                      "year":"2017"
                   },
                   "time":"14:20",
                   "defaultSector":"00005684",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53979047/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53979010",
                   "price":25.08,
                   "type":[
                      "Dublado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T17:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T17:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:00",
                      "year":"2017"
                   },
                   "time":"17:00",
                   "defaultSector":"00005684",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53979010/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"19777",
       "title":"Atômica",
       "originalTitle":"Atomic Blonde",
       "inPreSale":false,
       "duration":"115",
       "contentRating":"16 anos",
       "distributor":"Universal Pictures",
       "urlKey":"atomica",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/atomica",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/atomica#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19777-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19777-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=epxTk44F38g",
             "embeddedUrl":"//www.youtube.com/embed/epxTk44F38g"
          },
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=85Ge3CIBpJk",
             "embeddedUrl":"//www.youtube.com/embed/85Ge3CIBpJk"
          }
       ],
       "genres":[
          "Ação",
          "Thriller"
       ],
       "tags":[
          "Em Alta"
       ],
       "rooms":[
          {
             "name":"Sala 7",
             "sessions":[
                {
                   "id":"53953492",
                   "price":25.08,
                   "type":[
                      "Legendado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T22:20:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"22:20",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T22:20:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"22:20",
                      "year":"2017"
                   },
                   "time":"22:20",
                   "defaultSector":"00005681",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953492/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"19843",
       "title":"Polícia Federal - A lei é para todos",
       "originalTitle":"Polícia Federal - A lei é para todos",
       "inPreSale":false,
       "duration":"110",
       "contentRating":"12 anos",
       "distributor":"Downtown Filmes",
       "urlKey":"policia-federal-a-lei-e-para-todos",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/policia-federal-a-lei-e-para-todos",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/policia-federal-a-lei-e-para-todos#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19843-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19843-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=kUP0MLsvpOY",
             "embeddedUrl":"//www.youtube.com/embed/kUP0MLsvpOY"
          }
       ],
       "genres":[
          "Drama",
          "Policial"
       ],
       "tags":[
          "Em Alta"
       ],
       "rooms":[
          {
             "name":"Sala 3",
             "sessions":[
                {
                   "id":"53953491",
                   "price":51.3,
                   "type":[
                      "Nacional",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T15:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"15:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T15:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"15:00",
                      "year":"2017"
                   },
                   "time":"15:00",
                   "defaultSector":"00005677",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953491/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953494",
                   "price":51.3,
                   "type":[
                      "Nacional",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T18:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"18:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T18:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"18:00",
                      "year":"2017"
                   },
                   "time":"18:00",
                   "defaultSector":"00005677",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953494/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953478",
                   "price":51.3,
                   "type":[
                      "Nacional",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T21:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T21:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:00",
                      "year":"2017"
                   },
                   "time":"21:00",
                   "defaultSector":"00005677",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953478/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 4",
             "sessions":[
                {
                   "id":"53953390",
                   "price":51.3,
                   "type":[
                      "Nacional",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T14:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T14:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:00",
                      "year":"2017"
                   },
                   "time":"14:00",
                   "defaultSector":"00005678",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953390/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953332",
                   "price":51.3,
                   "type":[
                      "Nacional",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T17:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T17:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"17:00",
                      "year":"2017"
                   },
                   "time":"17:00",
                   "defaultSector":"00005678",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953332/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953500",
                   "price":51.3,
                   "type":[
                      "Nacional",
                      "Vip"
                   ],
                   "types":[
                      {
                         "id":2,
                         "name":"Vip",
                         "alias":"VIP",
                         "display":true
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T20:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"20:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T20:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"20:00",
                      "year":"2017"
                   },
                   "time":"20:00",
                   "defaultSector":"00005678",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953500/home",
                   "hasSeatSelection":true
                }
             ]
          },
          {
             "name":"Sala 6",
             "sessions":[
                {
                   "id":"53953381",
                   "price":25.08,
                   "type":[
                      "Nacional",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T16:15:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:15",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T16:15:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"16:15",
                      "year":"2017"
                   },
                   "time":"16:15",
                   "defaultSector":"00005680",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953381/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953408",
                   "price":25.08,
                   "type":[
                      "Nacional",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T18:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"18:45",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T18:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"18:45",
                      "year":"2017"
                   },
                   "time":"18:45",
                   "defaultSector":"00005680",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953408/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953467",
                   "price":25.08,
                   "type":[
                      "Nacional",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Nacional",
                         "alias":"NAC",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T21:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T21:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"21:30",
                      "year":"2017"
                   },
                   "time":"21:30",
                   "defaultSector":"00005680",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953467/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"19873",
       "title":"Em Defesa de Cristo",
       "originalTitle":"The Case for Christ,",
       "inPreSale":false,
       "duration":"112",
       "contentRating":"12 anos",
       "distributor":"California Filmes",
       "urlKey":"em-defesa-de-cristo",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/em-defesa-de-cristo",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/em-defesa-de-cristo#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19873-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/19873-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=0EFppdsg-LQ",
             "embeddedUrl":"//www.youtube.com/embed/0EFppdsg-LQ"
          }
       ],
       "genres":[
          "Drama"
       ],
       "tags":[

       ],
       "rooms":[
          {
             "name":"Sala 8",
             "sessions":[
                {
                   "id":"53953373",
                   "price":25.08,
                   "type":[
                      "Dublado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T14:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:00",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T14:00:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"14:00",
                      "year":"2017"
                   },
                   "time":"14:00",
                   "defaultSector":"00005682",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953373/home",
                   "hasSeatSelection":true
                },
                {
                   "id":"53953385",
                   "price":25.08,
                   "type":[
                      "Dublado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Dublado",
                         "alias":"DUB",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T19:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:45",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T19:45:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:45",
                      "year":"2017"
                   },
                   "time":"19:45",
                   "defaultSector":"00005682",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53953385/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    },
    {
       "id":"7834",
       "title":"O Jantar",
       "originalTitle":"The Dinner",
       "inPreSale":false,
       "duration":"120",
       "contentRating":"16 anos",
       "distributor":"California Filmes",
       "urlKey":"o-jantar",
       "siteURL":"https://www.ingresso.com/fortaleza/home/filmes/o-jantar",
       "siteURLByTheater":"https://www.ingresso.com/fortaleza/home/filmes/o-jantar#cinema=cinepolis-rio-mar",
       "images":[
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/7834-cartaz.jpg",
             "type":"PosterPortrait"
          },
          {
             "url":"https://ingresso-a.akamaihd.net/img/cinema/cartaz/7834-destaque.jpg",
             "type":"PosterHorizontal"
          }
       ],
       "trailers":[
          {
             "type":"Youtube",
             "url":"https://www.youtube.com/watch?v=mPKGjAofi8M",
             "embeddedUrl":"//www.youtube.com/embed/mPKGjAofi8M"
          }
       ],
       "genres":[
          "Drama",
          "Suspense"
       ],
       "tags":[

       ],
       "rooms":[
          {
             "name":"Sala 10",
             "sessions":[
                {
                   "id":"53982751",
                   "price":25.08,
                   "type":[
                      "Legendado",
                      "Normal"
                   ],
                   "types":[
                      {
                         "id":1,
                         "name":"Normal",
                         "alias":"2D",
                         "display":false
                      },
                      {
                         "id":0,
                         "name":"Legendado",
                         "alias":"LEG",
                         "display":true
                      }
                   ],
                   "date":{
                      "localDate":"2017-09-19T19:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:30",
                      "year":"2017"
                   },
                   "realDate":{
                      "localDate":"2017-09-19T19:30:00-03:00",
                      "isToday":true,
                      "dayOfWeek":"terça-feira",
                      "dayAndMonth":"19/09",
                      "hour":"19:30",
                      "year":"2017"
                   },
                   "time":"19:30",
                   "defaultSector":"00005684",
                   "siteURL":"https://carrinho.ingresso.com/checkout/#/adicionar/53982751/home",
                   "hasSeatSelection":true
                }
             ]
          }
       ]
    }
  ];